add_newline = false 

[character]
success_symbol = "[ 󱞪](#ffffff)"
error_symbol = "[ 󱞪](#ffffff)"
vicmd_symbol = "[ 󱞪❯](#ffffff)"

[username]
disabled = true
show_always = true
format = "[  $user ](b:none fg:#ffffff bold)"

[hostname]
disabled = true
ssh_only = false
format = "[ 󰌽 $hostname ]( bg:none fg:#ffffff bold)"

[directory]
disabled =false
format = "[  $path ](bg:#none fg:#ffffff bold)"
truncation_length = 3
truncate_to_repo=false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Videos" = " "
"iso" = "󰌽 "
".config" = ""

[git_branch]
disabled =false
format = '[  $branch ](bg:none fg:#ffffff bold)'

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = true
format = '[ 󱑆 $duration ](bg:none fg:#ffffff bold)'

